//! Fractional Dust Accounting for Multi-Signer Refunds
//! 
//! This module ensures that 100% of fractional dust generated by multi-signer refunds
//! is accounted for, preventing token loss through rounding errors.

use soroban_sdk::{i128, u64, Address, Env, Vec};
use crate::{safe_add, safe_sub, safe_mul};

/// Dust accounting structure for multi-signer refunds
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DustAccounting {
    /// Total dust tracked across all operations
    pub total_dust: i128,
    /// Dust per lease for precise tracking
    pub lease_dust: Vec<(u64, i128)>,
    /// Dust per signer for multi-signer operations
    pub signer_dust: Vec<(Address, i128)>,
    /// Cumulative dust recovered
    pub dust_recovered: i128,
    /// Number of dust operations performed
    pub dust_operations: u64,
}

impl DustAccounting {
    pub fn new() -> Self {
        Self {
            total_dust: 0,
            lease_dust: Vec::new(&Env::default()),
            signer_dust: Vec::new(&Env::default()),
            dust_recovered: 0,
            dust_operations: 0,
        }
    }

    /// Calculate and track dust from multi-signer refund
    pub fn calculate_multi_signer_dust(
        &mut self,
        total_amount: i128,
        signer_ratios: &[(Address, u32)], // (signer, basis_points)
        lease_id: u64,
        env: &Env
    ) -> Result<MultiSignerDustResult, DustAccountingError> {
        if total_amount < 0 {
            return Err(DustAccountingError::NegativeAmount(total_amount));
        }

        // Verify basis points sum
        let total_bps: u32 = signer_ratios.iter().map(|(_, bps)| *bps).sum();
        if total_bps > 10000 {
            return Err(DustAccountingError::InvalidBasisPointsSum(total_bps));
        }

        // Calculate individual shares and track dust
        let mut individual_shares = Vec::new(env);
        let mut allocated_amount = 0i128;
        let mut dust_for_lease = 0i128;

        for (i, (signer, bps)) in signer_ratios.iter().enumerate() {
            let is_last_signer = i == signer_ratios.len() - 1;
            
            let share = if is_last_signer {
                // Last signer gets all remaining amount (including dust)
                total_amount - allocated_amount
            } else {
                // Calculate share using integer division
                let raw_share = safe_mul(total_amount, *bps as i128)?;
                raw_share / 10000i128
            };

            individual_shares.push((signer.clone(), share));
            allocated_amount = safe_add(allocated_amount, share)?;

            // Track dust for non-last signers
            if !is_last_signer {
                let expected_share = safe_mul(total_amount, *bps as i128)? / 10000i128;
                let actual_share = share;
                let dust_diff = expected_share - actual_share;
                dust_for_lease = safe_add(dust_for_lease, dust_diff)?;
            }
        }

        // Verify dust accounting: sum must equal total exactly
        let actual_sum: i128 = individual_shares.iter().map(|(_, share)| *share).sum();
        if actual_sum != total_amount {
            return Err(DustAccountingError::DustAccountingMismatch {
                expected: total_amount,
                actual: actual_sum,
                dust_tracked: dust_for_lease,
            });
        }

        // Update dust tracking
        self.total_dust = safe_add(self.total_dust, dust_for_lease)?;
        self.lease_dust.push((lease_id, dust_for_lease));
        self.dust_operations += 1;

        // Track signer dust
        for (signer, share) in &individual_shares {
            let expected_share = safe_mul(total_amount, 
                signer_ratios.iter().find(|(s, _)| s == signer).unwrap().1 as i128)? / 10000i128;
            let signer_dust = expected_share - *share;
            if signer_dust > 0 {
                self.signer_dust.push((signer.clone(), signer_dust));
            }
        }

        Ok(MultiSignerDustResult {
            individual_shares,
            dust_amount: dust_for_lease,
            lease_id,
            verification_passed: true,
        })
    }

    /// Calculate dust from partial settlement operations
    pub fn calculate_partial_settlement_dust(
        &mut self,
        total_available: i128,
        settlement_amounts: &[i128],
        lease_id: u64,
        env: &Env
    ) -> Result<PartialSettlementDustResult, DustAccountingError> {
        if total_available < 0 {
            return Err(DustAccountingError::NegativeAmount(total_available));
        }

        // Verify all settlement amounts are non-negative
        for amount in settlement_amounts {
            if *amount < 0 {
                return Err(DustAccountingError::NegativeSettlementAmount(*amount));
            }
        }

        let total_settlement: i128 = settlement_amounts.iter().sum();
        
        if total_settlement > total_available {
            return Err(DustAccountingError::SettlementExceedsAvailable {
                settlement: total_settlement,
                available: total_available,
            });
        }

        // Calculate dust
        let dust = total_available - total_settlement;
        
        // Update dust tracking
        self.total_dust = safe_add(self.total_dust, dust)?;
        self.lease_dust.push((lease_id, dust));
        self.dust_operations += 1;

        Ok(PartialSettlementDustResult {
            settlement_amounts: settlement_amounts.to_vec(),
            dust_amount: dust,
            remaining_amount: dust,
            lease_id,
        })
    }

    /// Recover dust from lease operations
    pub fn recover_dust(&mut self, lease_id: u64, amount: i128) -> Result<(), DustAccountingError> {
        if amount < 0 {
            return Err(DustAccountingError::NegativeRecoveryAmount(amount));
        }

        // Find dust for this lease
        let lease_dust_index = self.lease_dust.iter().position(|(id, _)| *id == lease_id);
        
        if let Some(index) = lease_dust_index {
            let (_, dust_amount) = self.lease_dust.get(index).unwrap();
            
            if amount > *dust_amount {
                return Err(DustAccountingError::RecoveryExceedsDust {
                    recovery: amount,
                    available: *dust_amount,
                });
            }

            // Update dust tracking
            self.total_dust = safe_sub(self.total_dust, amount)?;
            self.dust_recovered = safe_add(self.dust_recovered, amount)?;
            
            // Update lease dust
            let remaining_dust = safe_sub(*dust_amount, amount)?;
            if remaining_dust == 0 {
                self.lease_dust.remove(index);
            } else {
                self.lease_dust.set(index, (lease_id, remaining_dust));
            }
        } else {
            return Err(DustAccountingError::NoDustForLease(lease_id));
        }

        Ok(())
    }

    /// Verify dust accounting integrity
    pub fn verify_dust_accounting(&self) -> Result<(), DustAccountingError> {
        // Property 1: Total dust must be non-negative
        if self.total_dust < 0 {
            return Err(DustAccountingError::NegativeTotalDust(self.total_dust));
        }

        // Property 2: Dust recovered must not exceed total dust
        if self.dust_recovered > self.total_dust {
            return Err(DustAccountingError::RecoveryExceedsTotal {
                recovered: self.dust_recovered,
                total: self.total_dust,
            });
        }

        // Property 3: Lease dust sum must equal total dust
        let lease_dust_sum: i128 = self.lease_dust.iter().map(|(_, amount)| *amount).sum();
        if lease_dust_sum != self.total_dust {
            return Err(DustAccountingError::LeaseDustMismatch {
                lease_sum: lease_dust_sum,
                total_dust: self.total_dust,
            });
        }

        // Property 4: Signer dust must be accounted for
        let signer_dust_sum: i128 = self.signer_dust.iter().map(|(_, amount)| *amount).sum();
        if signer_dust_sum > self.total_dust {
            return Err(DustAccountingError::SignerDustExceedsTotal {
                signer_sum: signer_dust_sum,
                total_dust: self.total_dust,
            });
        }

        Ok(())
    }

    /// Get comprehensive dust accounting report
    pub fn get_dust_report(&self) -> DustAccountingReport {
        DustAccountingReport {
            total_dust: self.total_dust,
            dust_recovered: self.dust_recovered,
            dust_operations: self.dust_operations,
            active_leases_with_dust: self.lease_dust.len(),
            active_signers_with_dust: self.signer_dust.len(),
            net_dust: self.total_dust - self.dust_recovered,
            accounting_verified: self.verify_dust_accounting().is_ok(),
        }
    }

    /// Reset dust accounting
    pub fn reset(&mut self, env: &Env) {
        *self = Self::new();
    }
}

/// Multi-signer dust calculation result
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MultiSignerDustResult {
    pub individual_shares: Vec<(Address, i128)>,
    pub dust_amount: i128,
    pub lease_id: u64,
    pub verification_passed: bool,
}

/// Partial settlement dust calculation result
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PartialSettlementDustResult {
    pub settlement_amounts: Vec<i128>,
    pub dust_amount: i128,
    pub remaining_amount: i128,
    pub lease_id: u64,
}

/// Dust accounting report
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DustAccountingReport {
    pub total_dust: i128,
    pub dust_recovered: i128,
    pub dust_operations: u64,
    pub active_leases_with_dust: u32,
    pub active_signers_with_dust: u32,
    pub net_dust: i128,
    pub accounting_verified: bool,
}

/// Dust accounting error types
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DustAccountingError {
    NegativeAmount(i128),
    NegativeSettlementAmount(i128),
    NegativeRecoveryAmount(i128),
    InvalidBasisPointsSum(u32),
    DustAccountingMismatch {
        expected: i128,
        actual: i128,
        dust_tracked: i128,
    },
    SettlementExceedsAvailable {
        settlement: i128,
        available: i128,
    },
    RecoveryExceedsDust {
        recovery: i128,
        available: i128,
    },
    NoDustForLease(u64),
    NegativeTotalDust(i128),
    RecoveryExceedsTotal {
        recovered: i128,
        total: i128,
    },
    LeaseDustMismatch {
        lease_sum: i128,
        total_dust: i128,
    },
    SignerDustExceedsTotal {
        signer_sum: i128,
        total_dust: i128,
    },
}

/// Property-based testing for dust accounting
pub fn dust_accounting_properties() {
    use proptest::prelude::*;
    
    proptest!(|(
        total_amount in 1i128..=1_000_000i128,
        signer_count in 2u32..=10u32,
        // Generate potentially problematic basis points
        bps_values in prop::collection::vec(0u32..=10000u32, 2..=10)
    )| {
        let env = Env::default();
        let mut dust_accounting = DustAccounting::new();
        
        let actual_signers = signer_count.min(bps_values.len() as u32);
        let used_bps = &bps_values[0..actual_signers as usize];
        
        // Create signers
        let mut signers = Vec::new(&env);
        let mut total_bps = 0u32;
        
        for (i, &bps) in used_bps.iter().enumerate() {
            let signer = Address::generate(&env);
            signers.push((signer, bps));
            total_bps += bps;
        }
        
        // Adjust last signer to ensure total doesn't exceed 10000
        if total_bps > 10000 && !signers.is_empty() {
            let excess = total_bps - 10000;
            let last_index = signers.len() - 1;
            let (signer, bps) = signers.get(last_index).unwrap();
            let adjusted_bps = bps.saturating_sub(excess);
            signers.set(last_index, (signer.clone(), adjusted_bps));
        }
        
        // Property 1: Multi-signer dust accounting preserves total value
        if total_bps <= 10000 {
            let result = dust_accounting.calculate_multi_signer_dust(
                total_amount, 
                &signers.to_vec(), 
                1, 
                &env
            );
            
            if let Ok(dust_result) = result {
                // Verify individual shares sum to total
                let share_sum: i128 = dust_result.individual_shares.iter().map(|(_, share)| *share).sum();
                prop_assert_eq!(share_sum, total_amount, 
                    "Share sum mismatch: {} != {}", share_sum, total_amount);
                
                // Verify all shares are non-negative
                for (_, share) in &dust_result.individual_shares {
                    prop_assert!(*share >= 0, "Negative share detected: {}", share);
                }
                
                // Verify no share exceeds total
                for (_, share) in &dust_result.individual_shares {
                    prop_assert!(*share <= total_amount, 
                        "Share {} exceeds total {}", share, total_amount);
                }
                
                // Verify dust is tracked correctly
                let expected_dust = if total_amount > 0 {
                    let exact_shares: i128 = signers.iter().map(|(_, bps)| 
                        (total_amount * *bps as i128) / 10000i128).sum();
                    total_amount - exact_shares
                } else {
                    0
                };
                
                prop_assert_eq!(dust_result.dust_amount, expected_dust,
                    "Dust amount mismatch: expected {}, got {}", expected_dust, dust_result.dust_amount);
            }
        }
        
        // Property 2: Dust accounting integrity is maintained
        let verification_result = dust_accounting.verify_dust_accounting();
        prop_assert!(verification_result.is_ok(), 
            "Dust accounting verification failed: {:?}", verification_result);
        
        // Property 3: Dust recovery works correctly
        if dust_accounting.total_dust > 0 {
            let recovery_amount = dust_accounting.total_dust / 2;
            let recovery_result = dust_accounting.recover_dust(1, recovery_amount);
            
            if recovery_result.is_ok() {
                prop_assert!(dust_accounting.dust_recovered >= recovery_amount,
                    "Dust recovery tracking incorrect");
            }
        }
    });
}

/// Extreme value testing for dust accounting
pub fn test_extreme_dust_values() {
    let env = Env::default();
    let mut dust_accounting = DustAccounting::new();
    
    // Test maximum values
    let max_amount = i128::MAX / 10000;
    let signers = vec![
        (Address::generate(&env), 5000),
        (Address::generate(&env), 5000),
    ];
    
    let result = dust_accounting.calculate_multi_signer_dust(max_amount, &signers, 1, &env);
    assert!(result.is_ok());
    
    // Test edge case with odd numbers
    let odd_amount = 1001i128;
    let signers = vec![
        (Address::generate(&env), 3333),
        (Address::generate(&env), 3333),
        (Address::generate(&env), 3334),
    ];
    
    let result = dust_accounting.calculate_multi_signer_dust(odd_amount, &signers, 2, &env);
    assert!(result.is_ok());
    
    if let Ok(dust_result) = result {
        // Verify dust is handled correctly
        let share_sum: i128 = dust_result.individual_shares.iter().map(|(_, share)| *share).sum();
        assert_eq!(share_sum, odd_amount);
    }
    
    // Test dust recovery
    if dust_accounting.total_dust > 0 {
        let recovery_result = dust_accounting.recover_dust(1, dust_accounting.total_dust);
        assert!(recovery_result.is_ok());
    }
    
    // Verify final state
    let verification_result = dust_accounting.verify_dust_accounting();
    assert!(verification_result.is_ok());
}

/// Comprehensive dust accounting verification
pub fn verify_dust_accounting_comprehensive() -> DustAccounting {
    let env = Env::default();
    let mut dust_accounting = DustAccounting::new();
    
    // Test various scenarios
    let test_cases = vec![
        (1000, vec![(5000, 5000)]), // 50/50 split
        (1001, vec![(3333, 3333, 3334)]), // 1/3 split with odd number
        (10000, vec![(1000, 2000, 3000, 4000)]), // Uneven split
        (999, vec![(1, 9999)]), // Extreme split
        (1, vec![(10000)]), // Single signer
    ];
    
    for (i, (amount, bps_splits)) in test_cases.iter().enumerate() {
        let mut signers = Vec::new(&env);
        for (j, &bps) in bps_splits.iter().enumerate() {
            let signer = Address::generate(&env);
            signers.push((signer, bps));
        }
        
        let _ = dust_accounting.calculate_multi_signer_dust(*amount, &signers, i as u64 + 1, &env);
    }
    
    // Verify all operations
    let verification_result = dust_accounting.verify_dust_accounting();
    assert!(verification_result.is_ok());
    
    dust_accounting
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    #[test]
    fn test_basic_dust_accounting() {
        let env = Env::default();
        let mut dust_accounting = DustAccounting::new();
        
        let signers = vec![
            (Address::generate(&env), 5000),
            (Address::generate(&env), 5000),
        ];
        
        let result = dust_accounting.calculate_multi_signer_dust(1000, &signers, 1, &env);
        assert!(result.is_ok());
        
        let dust_result = result.unwrap();
        assert_eq!(dust_result.individual_shares.len(), 2);
        
        let share_sum: i128 = dust_result.individual_shares.iter().map(|(_, share)| *share).sum();
        assert_eq!(share_sum, 1000);
    }

    #[test]
    fn test_dust_with_odd_amount() {
        let env = Env::default();
        let mut dust_accounting = DustAccounting::new();
        
        let signers = vec![
            (Address::generate(&env), 3333),
            (Address::generate(&env), 3333),
            (Address::generate(&env), 3334),
        ];
        
        let result = dust_accounting.calculate_multi_signer_dust(1001, &signers, 1, &env);
        assert!(result.is_ok());
        
        let dust_result = result.unwrap();
        
        // Last signer should get the dust
        let last_signer_share = dust_result.individual_shares.get(2).unwrap().1;
        assert!(last_signer_share >= 334); // Should get at least the fair share plus dust
        
        let share_sum: i128 = dust_result.individual_shares.iter().map(|(_, share)| *share).sum();
        assert_eq!(share_sum, 1001);
    }

    #[test]
    fn test_dust_recovery() {
        let env = Env::default();
        let mut dust_accounting = DustAccounting::new();
        
        let signers = vec![
            (Address::generate(&env), 5000),
            (Address::generate(&env), 5000),
        ];
        
        // Create some dust
        let _ = dust_accounting.calculate_multi_signer_dust(1001, &signers, 1, &env);
        
        // Recover dust
        if dust_accounting.total_dust > 0 {
            let result = dust_accounting.recover_dust(1, dust_accounting.total_dust);
            assert!(result.is_ok());
        }
        
        // Verify accounting
        let verification_result = dust_accounting.verify_dust_accounting();
        assert!(verification_result.is_ok());
    }

    #[test]
    fn test_property_based_dust_accounting() {
        dust_accounting_properties();
        test_extreme_dust_values();
    }

    #[test]
    fn test_comprehensive_dust_verification() {
        let dust_accounting = verify_dust_accounting_comprehensive();
        let report = dust_accounting.get_dust_report();
        
        assert!(report.accounting_verified);
        assert!(report.total_dust >= 0);
        assert!(report.dust_recovered >= 0);
        assert!(report.net_dust >= 0);
    }
}
